name: Setup Google Cloud SDK
author: Mathrix Education SA
description: Setup Google Cloud SDK on Github Actions.
branding:
  color: blue
  icon: upload-cloud
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  version:
    description: Google Cloud SDK to use. If left empty, will use the latest one. On Ubuntu runners, "local" allow to use the pre-installed version of gcloud.
    required: false
    default: 'latest'
  service-account-key:
    description: The service account key to use, base64-encoded.
    required: false
  project:
    description: The default Google Cloud project. You can change it later.
    required: false
    default: 'auto'
  components:
    description: Install additional components (e.g. beta, gsutil, etc.)
    required: false
  configure-docker:
    description: Configure Docker to interact with Google Cloud Container Registry. Use true for all repositories, or specify comma-separated registries.
    required: false
    default: 'false'
